### ISSUE TITLE
Throws an error for non-parsable types

### ISSUE THREAD

**Issue by nandorojo** [TooTallNate/spotify-uri#11]
Hey, thanks a lot for the library. There is an issue that breaks the entire app by throwing an error if `parse` can't find a URL. I think it should error silently.

Try: 

```js
const parsed = spotifyUri.parse('https://api.spotify.com/v1/tracks/7ytR5pFWmSjzHJIeQkgog4')
const url = parsed?.toEmbedURL()
const type = parsed.type
```

Results in:

![image](https://user-images.githubusercontent.com/13172299/97319249-15a5e080-1843-11eb-99b4-03fe2bfe52ba.png)

If this is intended behavior, the readme should have the code in a try-catch. It's unlikely to always have perfect data.

**Comment by TooTallNate** [comment]
We should update it to return `null`. Pull request welcome!

**Comment by Kikobeats** [comment]
This is an expected behavior

https://github.com/TooTallNate/spotify-uri/blob/ae97f32d5f6d7c6c78a04c94fd78153e747a2b5f/src/parse.ts#L96

Eventually, we can return a `null` rather than throw an error, but I think it's easy to workaround with a try/catch and returning `null` under error.
