### ISSUE TITLE
Support link.tospotify.com

### ISSUE THREAD

**Issue by KeepSOBP** [TooTallNate/spotify-uri#12]
Spotify mobile changed open.spotify.com to link.tospotify.com

Example) https://open.spotify.com/track/1pKYYY0dkg23sQQXi0Q5zN -> https://link.tospotify.com/VM2myZxXwbb

**Comment by TooTallNate** [comment]
Interesting! How are other "types" represented (album, artist, etc.?

**Comment by KeepSOBP** [comment]
Types are same, example)
playlist
https://link.tospotify.com/siNai64Wwbb

track
https://link.tospotify.com/9EgQaAaXwbb

Artist
https://link.tospotify.com/my18BpcXwbb

**Comment by KeepSOBP** [comment]
![Screenshot_20201119-160329_Chrome](https://user-images.githubusercontent.com/50764666/99632567-cbe69980-2a80-11eb-86a6-d0e25251e014.jpg)
Its shorten link, possible to support it?

**Comment by TooTallNate** [comment]
I see. So we would need to figure out how the shortlink hash is calculated, if it's even deterministic at all that is…
