### ISSUE TITLE
Not able to parse embed playlist urls

### ISSUE THREAD

**Issue by RickyMarou** [TooTallNate/spotify-uri#17]
example: `"https://open.spotify.com/embed/playlist/7arbVhvtYYaLYJefoRBSvU?utm_source=generator"`

parsing that string made the `.parse` function throw an error `TypeError: Could not determine type for: https://open.spotify.com/embed/playlist/7arbVhvtYYaLYJefoRBSvU?utm_source=generator`

**Comment by Kikobeats** [comment]
Hey, Thanks for reporting.

Released at https://github.com/TooTallNate/spotify-uri/releases/tag/v2.2.2 🎉

**Comment by RickyMarou** [comment]
What the hell @Kikobeats I love you so much, that was so quick !!! 

Thank you a thousand time for your help today ❤️

**Comment by Kikobeats** [comment]
You're very welcome! Please feel free to report any other bug 🙂
