### ISSUE TITLE
Module '"spotify-uri"' declares 'Playlist' locally, but it is not exported.ts(2459)

### ISSUE THREAD

**Issue by JMTK** [TooTallNate/spotify-uri#22]
After upgrading the package version from this week, I'm getting a new error:
![image](https://user-images.githubusercontent.com/877114/162462384-cdcb60ff-391c-4cee-bcbf-8c74deb3c848.png)
![image](https://user-images.githubusercontent.com/877114/162462651-f1dfe423-6b8d-44a3-ad4d-4047b7ae5606.png)

**Comment by Kikobeats** [comment]
Hum, it looks like TypeSscript types problem, but not sure how to resolve it.

This is the generated file published at npm:
https://unpkg.com/browse/spotify-uri@3.0.1/dist/index.d.ts

**Comment by JMTK** [comment]
When I add `export` it works fine. I actually don't know what `declare` is adding here:
![image](https://user-images.githubusercontent.com/877114/162548412-392700a7-1f50-4e79-97ae-0c8a6e4ec3b3.png)
![image](https://user-images.githubusercontent.com/877114/162548420-62c705ad-de1e-43c4-bf9a-0d6f06172fb3.png)

Both work as expected

**Comment by Lioness100** [comment]
But that's just the type- the actual class itself isn't exported anymore either.
https://github.com/TooTallNate/spotify-uri/commit/af66e4f1d2f0e382951cf7c2685eca6444364d0c#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

**Comment by Lioness100** [comment]
This could fix the issue very easily, no?

```diff
- export { parse }
+ export {
+    	parse,
+    	Search,
+ 		Episode,
+ 		Local,
+ 		Playlist,
+ 		Track,
+ 		Artist,
+		Album,
+		User,
+ }
```

**Comment by Kikobeats** [comment]
yup; can you make a PR?

**Comment by Lioness100** [comment]
Sure
