### ISSUE TITLE
Reading URL constructor from global 

### ISSUE THREAD

**Issue by roderickhsiao** [TooTallNate/spotify-uri#24]
Thanks for providing the library! Super helpful and well written!

One thing for importing `URL` constructor, 
```js
import { URL } from 'url'
```
https://github.com/TooTallNate/spotify-uri/blob/master/src/parse.ts#L1 

We are now importing URL from the module, which makes the library depends on `url` library in the browser. 
Node 10 start fully supports `URL` in global, we could directly access it without importing from the `url` module.
This will help directly using `URL` in the browser (polyfill when needed). 

The library currently is targeting Node 12, so I believe the code should work fine but understand it could be breaking changes.

Thanks!

Related issue https://github.com/GoogleChromeLabs/native-url/pull/18

**Comment by Kikobeats** [comment]
Hello,

A solution could be to provide a way unified way to get `URL` constructor, like:

```ts
import { URL } from './util' 
```

```ts
// utils.ts
export const URL = global.window ? window.URL : require('url').URL
```

can you make a PR? 🙂

**Comment by roderickhsiao** [comment]
> Hello,
> 
> A solution could be to provide a way unified way to get `URL` constructor, like:
> 
> ```ts
> import { URL } from './util' 
> ```
> 
> ```ts
> // util.ts
> export const URL = global.window ? window.URL : require('url').URL
> ```
instead of assuming client/server, I just do it as fallback, let me know how you think
https://github.com/TooTallNate/spotify-uri/pull/25/files#diff-3294a832ea2276e554177e0b3007cc2d401c082912c7fbde49fa09141bf1aed1R21

> 
> can you make a PR? 🙂

**Comment by Kikobeats** [comment]
> instead of assuming client/server, I just do it as fallback, let me know how you think

in that way you can't take advantages of browser capabilities since `global` doesn't exist in a context browser.

**Comment by roderickhsiao** [comment]
Thanks for pointing out, I was thinking about `globalThis` when putting up PR, my intention is to not use `require('url').URL` as much as possible (in both node/browser) to use the newer implementation.
I changed to fallback to window if global does not exist.

**Comment by roderickhsiao** [comment]
Close per disucsion

**Comment by TooTallNate** [comment]
I'm in favor of using the `URL` global. Node < 10 is old news.

**Comment by salomoneb** [comment]
Hi, I know this is closed but I ran into this exact issue when I wanted to use the library in an isomorphic context. It would be great if this supported the global browser `URL`. I work on a large production application with a legacy, spaghetti-code bundler, and it's not the easiest thing in the world to make something like that compatible with this. 

I'd be happy to look into this further, though I was getting the following error when I tried to build `master` with `npm run build` (node v12.14.1): 

```sh
npm run build

> spotify-uri@3.0.3 prebuild
> rm -rf dist


> spotify-uri@3.0.3 build
> tsup src/index.ts --format esm,cjs --dts

/Users/salomonebaquis/Desktop/spotify-uri/node_modules/bundle-require/dist/index.js:22
import fs2 from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/salomonebaquis/Desktop/spotify-uri/node_modules/tsup/dist/chunk-247V7HL5.js:1239:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
(node:84252) Warning: require() of ES modules is not supported.
require() of /Users/salomonebaquis/Desktop/spotify-uri/node_modules/bundle-require/dist/index.js from /Users/salomonebaquis/Desktop/spotify-uri/node_modules/tsup/dist/chunk-247V7HL5.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/salomonebaquis/Desktop/spotify-uri/node_modules/bundle-require/package.json.
```
