### ISSUE TITLE
Bug: Parse Youtube Link

### ISSUE THREAD

**Issue by aiko-chan-ai** [TooTallNate/spotify-uri#26]
Preview: 
![image](https://user-images.githubusercontent.com/71698422/187061171-aabe8ae9-11f1-414c-9e0b-56f59cc857f6.png)

Code
```js
import * as spot from 'spotify-uri';
console.log(spot.parse('https://www.youtube.com/playlist?list=random'))
```

**Comment by Kikobeats** [comment]
This is a well known limitation. You have to check the domain before using the library 🙂
