### ISSUE TITLE
Support for "intl-XX" URLs

### ISSUE THREAD

**Issue by giorgi-o** [TooTallNate/spotify-uri#32]
A new URL variant seems to have popped up, for both songs and albums:

https://open.spotify.com/intl-fr/track/3g3YCqJbfTBhUbvmOauugY?si=37444d06697e44fa

https://open.spotify.com/intl-fr/album/7ovdjtmV0Bkm4Xb4pqtrZt?si=qYmaklK4ReSVvBjLqHfxew

Spotify automatically redirects these links to the versions without `intl-XX`, but it would be nice for this library to be able to parse them as-is.

**Comment by PawsOfDestruction** [comment]
+1

**Comment by giorgi-o** [comment]
Fixed in #35, tysm @Hatzilu!
