### ISSUE TITLE
[Request] support for epoisde and show

### ISSUE THREAD

**Issue by Dramex** [TooTallNate/spotify-uri#9]
example url:

https://open.spotify.com/episode/0jg4lF0x3MagoSIVIqUpl2?si=7BdFd6zsRCGrD3NhZIU1GQ
 https://open.spotify.com/show/3BAZ3s64p999y9Q7uCgffM?si=hN91iWsHSvqmDnJ3oGr-ig

**Comment by shem8** [comment]
add a [new PR](https://github.com/TooTallNate/spotify-uri/pull/10)
